---
kind: pipeline
type: kubernetes
name: default

steps:
- name: test
  image: node:lts-alpine
  commands:
  - npm install
  - npm test
- name: publish npm
  image: plugins/npm
  settings:
    username: r1cebank
    password:
      from_secret: npm_password
    email: siyuangao@gmail.com
